import { Footer } from '@/components/layouts/Footer/Footer'
import { Header } from '@/components/layouts/Header'
import { Provider } from '@/components/layouts/Provider'
import { stolzl } from '@/components/utils/font'
import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Lamborghini Rent',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={stolzl.className}>
				<Provider>
					<Header />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	)
}
