import { Provider } from '@/components/layouts/Provider'
import { stolzl } from '@/components/utils/font'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Lamborghini Rent',
	description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const locale = await getLocale()

	const messages = await getMessages()
	return (
		<html lang={locale}>
			<body className={stolzl.className}>
				<NextIntlClientProvider messages={messages}>
					<Provider>{children}</Provider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
